### ISSUE TITLE
Extremly slow uploads to hubiC

### ISSUE THREAD

**Issue by amemo06** [roikku/swift-explorer#49]
Hi, 
I face extremly slow transfer rate to upload files to hubiC.
From the hubiC web ui, I have usually around 16Mbps
BUT from Swift, the maximum I face is 1.6Mbps. 
10 times less !!

Any clue how to solves this ??

**Comment by roikku** [comment]
Upload speed of segmented files will likely be improved after the release of the next version of JOSS (see https://github.com/javaswift/joss/pull/70).
