### ISSUE TITLE
Upload big file is very slow

### ISSUE THREAD

**Issue by Nico83500** [roikku/swift-explorer#55]
Hi,
I have a 10 TB hubiC account and I would like to upload big files (about 15-20 GB) without using Windows sync client (because I don't want to keep all files). So I've tried Swift Explorer, it does the job but upload time is very slow. It splits file into 210 segments and each segment is slow to upload.
Is there a solution or an alternative ?
Thank you.

**Comment by murf0** [comment]
You need to do parallel upload for quick hubic uploads.Which is'nt supported in Swift-explorer.
I use [hubic-wrapper-to-swift](https://github.com/puzzle1536/hubic-wrapper-to-swift) for big uploads with ~10 parallel uploads. For me that maxes out my connection (100mpbs upload)

**Comment by roikku** [comment]
https://github.com/roikku/swift-explorer/issues/49
