### ISSUE TITLE
Problem when uploading a folder

### ISSUE THREAD

**Issue by arriflex2** [roikku/swift-explorer#7]
Hello ans thank you very much for this very useful app!

I have a problem when uploading a 13 video folder (5.5go )
The upload doen't work and a dialog box shows:
org.javaswift.joss.exception.CommandException: Unable to execute the HTTP call or to convert the HTTP Response

Only 1video on 13 is uploaded.

I work on Windows 7 w86 ans hubic free account.

Thank you!

**Comment by tedylou** [comment]
Hi,

I have the same message "unable to execute the HTTP.." when I try to download a very small directory. Only the name of the directory is downloaded. not any file inside.
when I only choose one file of this directory, it is uploaded, but its date is not the original one, but the current date. That is a real problem and I worry it is the same thing for a download of a directory.
And I have also this message when I only click on a big backuped directory in the browser. Immediately the message appears after 2 seconds. The directory is backed on hubic.
How these problems would be solved?
