### ISSUE TITLE
It doesn't work anymore with Hubic

### ISSUE THREAD

**Issue by carinej** [roikku/swift-explorer#76]
Hi, I can't access to my Hubic account through Swift Explorer. I have the message : "unable to execute the http call or to convert the http response". It used to work pefectly well before. What's wrong and how to solve it ? Regards,
Carine

**Comment by papaye** [comment]
bonjour,je crois que sa vient peut-etre  de [http://travaux.ovh.net/?do=details&id=26966](url)

**Comment by carinej** [comment]
Bonjour,
   merci pour votre retour rapide. Sauriez-vous jusqu'à quand ce pb peut durer car la maintenance a eu lieu le 31/08 ?
Bonne journée,
Carine Julcour

----- Mail original -----
De: "papaye" <notifications@github.com>
À: "roikku/swift-explorer" <swift-explorer@noreply.github.com>
Cc: "carinej" <carine.julcour@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Dimanche 3 Septembre 2017 13:47:13
Objet: Re: [roikku/swift-explorer] It doesn't work anymore with Hubic (#76)



bonjour,je crois que sa vient peut-etre de http://travaux.ovh.net/?do=details&id=26966

**Comment by papaye** [comment]
Re carinej ,je suis pas sur .je suis simple utilisateur mais j'ai constater le probléme depuis cette upgrade de OVH .je suppose qu'une mise a jour de SwiftExplorer pourrait résoudre ce problème.

**Comment by ngzero** [comment]
same problem here. can't access hubic with the latest version of swift explorer.

**Comment by tarkustr** [comment]
Même problème. Impossible d'accéder au contenu de l'espace de stockage.
`Unable  to execute the HTPP Call or to convert the HTPP response` . Cette application ne semble pas être 'déclarée' dans mon profil..Je pige pas.
Windows10- 64,

**Comment by RoReichert** [comment]
Same problem here with Mac Book Pro and Mac OS Sierra, 10.12.6, since a couple of weeks. Hope OVH will find an issue soon.

**Comment by thihen** [comment]
Same problem    : 
**Wed Sep 27 11:23:23 CEST 2017  -  Unable to execute the HTTP call or to convert the HTTP Response**
(Window10-64 (10.0.15063) - swift explorer 1.0.8)

**Comment by crequill** [comment]
Same problem here on an iMac with Mac OS Sierra 10.12.6 and switft explorer 1.0.8:
**Tue Oct 17 21:52:17 CEST 2017  -  Unable to execute the HTTP call or to convert the HTTP Response**

**Comment by roikku** [comment]
Should be fixed with the latest release.
